define augeas (
  $name       , # (namevar) The name of this task. Used for...
  $changes    , # The changes which should be applied to the...
  $context    , # Optional context path. This value is prepended...
  $force      , # Optional command to force the augeas type to...
  $incl       , # Load only a specific file, e.g. `/etc/hosts`...
  $lens       , # Use a specific lens, e.g. `Hosts.lns`. When this
  $load_path  , # Optional colon-separated list or array of...
  $onlyif     , # Optional augeas command and comparisons to...
  $provider   , # The specific backend to use for this `augeas...
  $returns    , # The expected return code from the augeas...
  $root       , # A file system path; all files loaded by Augeas...
  $show_diff  , # Whether to display differences when the file...
  $type_check , # Whether augeas should perform typechecking...
 )
{
}
