define cron (
  $name        , # (namevar) The symbolic name of the cron job.  This name is
  $ensure      , # The basic property that the resource should be...
  $command     , # The command to execute in the cron job.  The...
  $environment , # Any environment settings associated with this...
  $hour        , # The hour at which to run the cron job. Optional;
  $minute      , # The minute at which to run the cron job...
  $month       , # The month of the year.  Optional; if specified...
  $monthday    , # The day of the month on which to run the...
  $provider    , # The specific backend to use for this `cron...
  $special     , # A special value such as 'reboot' or 'annually'...
  $target      , # The name of the crontab file in which the cron...
  $user        , # The user who owns the cron job.  This user must...
  $weekday     , # The weekday on which to run the command...
  # ...plus any applicable metaparameters.
){
}