define exec (
  $command     , # (namevar) The actual command to execute.  Must either be...
  $creates     , # A file to look for before running the command...
  $cwd         , # The directory from which to run the command.  If
  $environment , # Any additional environment variables you want to
  $group       , # The group to run the command as.  This seems to...
  $logoutput   , # Whether to log command output in addition to...
  $onlyif      , # If this parameter is set, then this `exec` will...
  $path        , # The search path used for command execution...
  $provider    , # The specific backend to use for this `exec...
  $refresh     , # How to refresh this command.  By default, the...
  $refreshonly , # The command should only be run as a refresh...
  $returns     , # The expected exit code(s).  An error will be...
  $timeout     , # The maximum time the command should take.  If...
  $tries       , # The number of times execution of the command...
  $try_sleep   , # The time to sleep in seconds between...
  $umask       , # Sets the umask to be used while executing this...
  $unless      , # If this parameter is set, then this `exec` will...
  $user

) {

}
