define group (
  $name                 , # (namevar) The group name. While naming limitations vary by
  $ensure               , # Create or remove the group.  Valid values are...
  $allowdupe            , # Whether to allow duplicate GIDs. Defaults to...
  $attribute_membership , # Whether specified attribute value pairs should...
  $attributes           , # Specify group AIX attributes in an array of...
  $auth_membership      , # whether the provider is authoritative for group...
  $forcelocal           , # Forces the management of local accounts when...
  $gid                  , # The group ID.  Must be specified numerically....
  $ia_load_module       , # The name of the I&A module to use to manage this
  $members              , # The members of the group. For directory services
  $provider             , # The specific backend to use for this `group...
  $system               , # Whether the group is a system group with lower...
  # ...plus any applicable metaparameters.
){}
