define host (
  $name         , # (namevar) The host...
  $ensure       , # The basic property that the resource should be...
  $comment      , # A comment that will be attached to the line with
  $host_aliases , # Any aliases the host might have.  Multiple...
  $ip           , # The host's IP address, IPv4 or...
  $provider     , # The specific backend to use for this `host...
  $target       , # The file in which to store service information.
  # ...plus any applicable metaparameters.
){}
