define interface (
  $name                , # (namevar) The interface's...
  $ensure              , # The basic property that the resource should be...
  $allowed_trunk_vlans , # Allowed list of Vlans that this trunk can...
  $description         , # Interface...
  $device_url          , # The URL at which the router or switch can be...
  $duplex              , # Interface duplex.  Valid values are `auto`...
  $encapsulation       , # Interface switchport encapsulation.  Valid...
  $etherchannel        , # Channel group this interface is part of.  Values
  $ipaddress           , # IP Address of this interface. Note that it might
  $mode                , # Interface switchport mode.  Valid values are...
  $native_vlan         , # Interface native vlan (for access mode only)....
  $provider            , # The specific backend to use for this `interface`
  $speed               , # Interface speed.  Valid values are `auto`...
  # ...plus any applicable metaparameters.
){}
