
define mount (
  $name        , # (namevar) The mount path for the...
  $ensure      , # Control what to do with this mount. Set this...
  $atboot      , # Whether to mount the mount at boot.  Not all...
  $blockdevice , # The device to fsck.  This is property is only...
  $device      , # The device providing the mount.  This can be...
  $dump        , # Whether to dump the mount.  Not all platform...
  $fstype      , # The mount type.  Valid values depend on the...
  $options     , # A single string containing options for the...
  $pass        , # The pass in which the mount is...
  $provider    , # The specific backend to use for this `mount...
  $remounts    , # Whether the mount can be remounted  `mount -o...
  $target      , # The file in which to store the mount table....
  # ...plus any applicable metaparameters.
){}