define package (
  $provider             , # (namevar) The specific backend to use for this `package...
  $name                 , # (namevar) The package name.  This is the name that the...
  $ensure               , # What state the package should be in. On...
  $adminfile            , # A file containing package defaults for...
  $allow_virtual        , # Specifies if virtual package names are allowed...
  $allowcdrom           , # Tells apt to allow cdrom sources in the...
  $category             , # A read-only parameter set by the...
  $configfiles          , # Whether configfiles should be kept or replaced.
  $description          , # A read-only parameter set by the...
  $flavor               , # OpenBSD supports 'flavors', which are further...
  $install_options      , # An array of additional options to pass when...
  $instance             , # A read-only parameter set by the...
  $package_settings     , # Settings that can change the contents or...
  $platform             , # A read-only parameter set by the...
  $reinstall_on_refresh , # Whether this resource should respond to refresh...
  $responsefile         , # A file containing any necessary answers to...
  $root                 , # A read-only parameter set by the...
  $source               , # Where to find the package file. This is only...
  $status               , # A read-only parameter set by the...
  $uninstall_options    , # An array of additional options to pass when...
  $vendor               , # A read-only parameter set by the...
) {}
