define ssh_authorized_key (
  $name     , # (namevar) The SSH key comment. This attribute is currently
  $ensure   , # The basic property that the resource should be...
  $key      , # The public key itself; generally a long string...
  $options  , # Key options; see sshd(8) for possible values...
  $provider , # The specific backend to use for this...
  $target   , # The absolute filename in which to store the SSH...
  $type     , # The encryption type used.  Valid values are...
  $user     , # The user account in which the SSH key should be...
  # ...plus any applicable metaparameters.
){}
